# Generated by Django 2.2.6 on 2019-12-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAnywhereApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
