# Generated by Django 2.2.6 on 2019-12-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectAnywhereApp', '0003_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='emailid',
            new_name='email',
        ),
    ]
